//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TP1ConsumBankWebService.lt.lb.webservices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BLiquiditySoap", Namespace="http://webservices.lb.lt/BLiquidity")]
    public partial class BLiquidity : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getBLiquidityRateTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLatestBLiquidityRateOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBLiquidityRateOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBLiquidityRatesByDate_XmlStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBLiquidityByRateType_XmlStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBLiquidityRatesByDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBLiquidityByRateTypeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BLiquidity() {
            this.Url = global::TP1ConsumBankWebService.Properties.Settings.Default.TP1ConsumBankWebService_lt_lb_webservices_BLiquidity;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getBLiquidityRateTypesCompletedEventHandler getBLiquidityRateTypesCompleted;
        
        /// <remarks/>
        public event getLatestBLiquidityRateCompletedEventHandler getLatestBLiquidityRateCompleted;
        
        /// <remarks/>
        public event getBLiquidityRateCompletedEventHandler getBLiquidityRateCompleted;
        
        /// <remarks/>
        public event getBLiquidityRatesByDate_XmlStringCompletedEventHandler getBLiquidityRatesByDate_XmlStringCompleted;
        
        /// <remarks/>
        public event getBLiquidityByRateType_XmlStringCompletedEventHandler getBLiquidityByRateType_XmlStringCompleted;
        
        /// <remarks/>
        public event getBLiquidityRatesByDateCompletedEventHandler getBLiquidityRatesByDateCompleted;
        
        /// <remarks/>
        public event getBLiquidityByRateTypeCompletedEventHandler getBLiquidityByRateTypeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.lb.lt/BLiquidity/getBLiquidityRateTypes", RequestNamespace="http://webservices.lb.lt/BLiquidity", ResponseNamespace="http://webservices.lb.lt/BLiquidity", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode getBLiquidityRateTypes() {
            object[] results = this.Invoke("getBLiquidityRateTypes", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void getBLiquidityRateTypesAsync() {
            this.getBLiquidityRateTypesAsync(null);
        }
        
        /// <remarks/>
        public void getBLiquidityRateTypesAsync(object userState) {
            if ((this.getBLiquidityRateTypesOperationCompleted == null)) {
                this.getBLiquidityRateTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBLiquidityRateTypesOperationCompleted);
            }
            this.InvokeAsync("getBLiquidityRateTypes", new object[0], this.getBLiquidityRateTypesOperationCompleted, userState);
        }
        
        private void OngetBLiquidityRateTypesOperationCompleted(object arg) {
            if ((this.getBLiquidityRateTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBLiquidityRateTypesCompleted(this, new getBLiquidityRateTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.lb.lt/BLiquidity/getLatestBLiquidityRate", RequestNamespace="http://webservices.lb.lt/BLiquidity", ResponseNamespace="http://webservices.lb.lt/BLiquidity", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal getLatestBLiquidityRate(string RateType) {
            object[] results = this.Invoke("getLatestBLiquidityRate", new object[] {
                        RateType});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void getLatestBLiquidityRateAsync(string RateType) {
            this.getLatestBLiquidityRateAsync(RateType, null);
        }
        
        /// <remarks/>
        public void getLatestBLiquidityRateAsync(string RateType, object userState) {
            if ((this.getLatestBLiquidityRateOperationCompleted == null)) {
                this.getLatestBLiquidityRateOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLatestBLiquidityRateOperationCompleted);
            }
            this.InvokeAsync("getLatestBLiquidityRate", new object[] {
                        RateType}, this.getLatestBLiquidityRateOperationCompleted, userState);
        }
        
        private void OngetLatestBLiquidityRateOperationCompleted(object arg) {
            if ((this.getLatestBLiquidityRateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLatestBLiquidityRateCompleted(this, new getLatestBLiquidityRateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.lb.lt/BLiquidity/getBLiquidityRate", RequestNamespace="http://webservices.lb.lt/BLiquidity", ResponseNamespace="http://webservices.lb.lt/BLiquidity", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal getBLiquidityRate(string RateType, string Date) {
            object[] results = this.Invoke("getBLiquidityRate", new object[] {
                        RateType,
                        Date});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void getBLiquidityRateAsync(string RateType, string Date) {
            this.getBLiquidityRateAsync(RateType, Date, null);
        }
        
        /// <remarks/>
        public void getBLiquidityRateAsync(string RateType, string Date, object userState) {
            if ((this.getBLiquidityRateOperationCompleted == null)) {
                this.getBLiquidityRateOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBLiquidityRateOperationCompleted);
            }
            this.InvokeAsync("getBLiquidityRate", new object[] {
                        RateType,
                        Date}, this.getBLiquidityRateOperationCompleted, userState);
        }
        
        private void OngetBLiquidityRateOperationCompleted(object arg) {
            if ((this.getBLiquidityRateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBLiquidityRateCompleted(this, new getBLiquidityRateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.lb.lt/BLiquidity/getBLiquidityRatesByDate_XmlString", RequestNamespace="http://webservices.lb.lt/BLiquidity", ResponseNamespace="http://webservices.lb.lt/BLiquidity", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getBLiquidityRatesByDate_XmlString(string Date) {
            object[] results = this.Invoke("getBLiquidityRatesByDate_XmlString", new object[] {
                        Date});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getBLiquidityRatesByDate_XmlStringAsync(string Date) {
            this.getBLiquidityRatesByDate_XmlStringAsync(Date, null);
        }
        
        /// <remarks/>
        public void getBLiquidityRatesByDate_XmlStringAsync(string Date, object userState) {
            if ((this.getBLiquidityRatesByDate_XmlStringOperationCompleted == null)) {
                this.getBLiquidityRatesByDate_XmlStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBLiquidityRatesByDate_XmlStringOperationCompleted);
            }
            this.InvokeAsync("getBLiquidityRatesByDate_XmlString", new object[] {
                        Date}, this.getBLiquidityRatesByDate_XmlStringOperationCompleted, userState);
        }
        
        private void OngetBLiquidityRatesByDate_XmlStringOperationCompleted(object arg) {
            if ((this.getBLiquidityRatesByDate_XmlStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBLiquidityRatesByDate_XmlStringCompleted(this, new getBLiquidityRatesByDate_XmlStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.lb.lt/BLiquidity/getBLiquidityByRateType_XmlString", RequestNamespace="http://webservices.lb.lt/BLiquidity", ResponseNamespace="http://webservices.lb.lt/BLiquidity", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getBLiquidityByRateType_XmlString(string RateType, string DateLow, string DateHigh) {
            object[] results = this.Invoke("getBLiquidityByRateType_XmlString", new object[] {
                        RateType,
                        DateLow,
                        DateHigh});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getBLiquidityByRateType_XmlStringAsync(string RateType, string DateLow, string DateHigh) {
            this.getBLiquidityByRateType_XmlStringAsync(RateType, DateLow, DateHigh, null);
        }
        
        /// <remarks/>
        public void getBLiquidityByRateType_XmlStringAsync(string RateType, string DateLow, string DateHigh, object userState) {
            if ((this.getBLiquidityByRateType_XmlStringOperationCompleted == null)) {
                this.getBLiquidityByRateType_XmlStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBLiquidityByRateType_XmlStringOperationCompleted);
            }
            this.InvokeAsync("getBLiquidityByRateType_XmlString", new object[] {
                        RateType,
                        DateLow,
                        DateHigh}, this.getBLiquidityByRateType_XmlStringOperationCompleted, userState);
        }
        
        private void OngetBLiquidityByRateType_XmlStringOperationCompleted(object arg) {
            if ((this.getBLiquidityByRateType_XmlStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBLiquidityByRateType_XmlStringCompleted(this, new getBLiquidityByRateType_XmlStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.lb.lt/BLiquidity/getBLiquidityRatesByDate", RequestNamespace="http://webservices.lb.lt/BLiquidity", ResponseNamespace="http://webservices.lb.lt/BLiquidity", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode getBLiquidityRatesByDate(string Date) {
            object[] results = this.Invoke("getBLiquidityRatesByDate", new object[] {
                        Date});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void getBLiquidityRatesByDateAsync(string Date) {
            this.getBLiquidityRatesByDateAsync(Date, null);
        }
        
        /// <remarks/>
        public void getBLiquidityRatesByDateAsync(string Date, object userState) {
            if ((this.getBLiquidityRatesByDateOperationCompleted == null)) {
                this.getBLiquidityRatesByDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBLiquidityRatesByDateOperationCompleted);
            }
            this.InvokeAsync("getBLiquidityRatesByDate", new object[] {
                        Date}, this.getBLiquidityRatesByDateOperationCompleted, userState);
        }
        
        private void OngetBLiquidityRatesByDateOperationCompleted(object arg) {
            if ((this.getBLiquidityRatesByDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBLiquidityRatesByDateCompleted(this, new getBLiquidityRatesByDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.lb.lt/BLiquidity/getBLiquidityByRateType", RequestNamespace="http://webservices.lb.lt/BLiquidity", ResponseNamespace="http://webservices.lb.lt/BLiquidity", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode getBLiquidityByRateType(string RateType, string DateLow, string DateHigh) {
            object[] results = this.Invoke("getBLiquidityByRateType", new object[] {
                        RateType,
                        DateLow,
                        DateHigh});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void getBLiquidityByRateTypeAsync(string RateType, string DateLow, string DateHigh) {
            this.getBLiquidityByRateTypeAsync(RateType, DateLow, DateHigh, null);
        }
        
        /// <remarks/>
        public void getBLiquidityByRateTypeAsync(string RateType, string DateLow, string DateHigh, object userState) {
            if ((this.getBLiquidityByRateTypeOperationCompleted == null)) {
                this.getBLiquidityByRateTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBLiquidityByRateTypeOperationCompleted);
            }
            this.InvokeAsync("getBLiquidityByRateType", new object[] {
                        RateType,
                        DateLow,
                        DateHigh}, this.getBLiquidityByRateTypeOperationCompleted, userState);
        }
        
        private void OngetBLiquidityByRateTypeOperationCompleted(object arg) {
            if ((this.getBLiquidityByRateTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBLiquidityByRateTypeCompleted(this, new getBLiquidityByRateTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getBLiquidityRateTypesCompletedEventHandler(object sender, getBLiquidityRateTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBLiquidityRateTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBLiquidityRateTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getLatestBLiquidityRateCompletedEventHandler(object sender, getLatestBLiquidityRateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLatestBLiquidityRateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLatestBLiquidityRateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getBLiquidityRateCompletedEventHandler(object sender, getBLiquidityRateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBLiquidityRateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBLiquidityRateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getBLiquidityRatesByDate_XmlStringCompletedEventHandler(object sender, getBLiquidityRatesByDate_XmlStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBLiquidityRatesByDate_XmlStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBLiquidityRatesByDate_XmlStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getBLiquidityByRateType_XmlStringCompletedEventHandler(object sender, getBLiquidityByRateType_XmlStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBLiquidityByRateType_XmlStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBLiquidityByRateType_XmlStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getBLiquidityRatesByDateCompletedEventHandler(object sender, getBLiquidityRatesByDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBLiquidityRatesByDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBLiquidityRatesByDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getBLiquidityByRateTypeCompletedEventHandler(object sender, getBLiquidityByRateTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBLiquidityByRateTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBLiquidityByRateTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591